### ISSUE TITLE
Duplikat, kann gelöscht werden? 

### ISSUE THREAD

**Issue by schuer** [akuehnis/redaxo5_addon_css_above_the_fold#2]
Der ehemalige Fork, der bereits weiter entwickelt ist als dieses Original, wurde neulich vom GitHub-Support (siehe [Kommentar](https://github.com/FriendsOfREDAXO/css_above_the_fold/issues/3#issuecomment-333403615)) zu einem Standalone-Repo umgewandelt und liegt hier: https://github.com/FriendsOfREDAXO/css_above_the_fold

Damit ist dieses Repo hier nun eigentlich obsolet und könnte aus meiner Sicht gelöscht werden?

**Comment by akuehnis** [comment]
Ach so, das wusste ich nicht. Kannst du es mir zurück transferieren (akuehnis), ich darf das nicht?
